version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: supabase_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: supabase_user
      POSTGRES_PASSWORD: supabase_password
      POSTGRES_DB: supabase_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: