name: journal_ofertas
description: Journal Ofertas Flutter App

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700

    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Bold.ttf
          weight: 700

    - family: RobotoFlex
      fonts:
        - asset: fonts/RobotoFlex-Bold.ttf
          weight: 700

  assets:
    - assets/images/
